const rows = document.querySelector('#attendanceRows'); const modal = document.querySelector('#detailsModal'); let selectedId = null;
const dateFormat = (date) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(new Date(`${date.replace(' ', 'T')}Z`));
async function api(url, options) { const response = await fetch(url, options); if (response.status === 204) return null; const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a ação.'); return data; }
function badge(status) { return `<span class="badge ${status.split(' ')[0]}">${status}</span>`; }
async function loadDashboard() { const metrics = await api('/api/atendimentos/dashboard'); document.querySelector('#total').textContent = metrics.total; document.querySelector('#pending').textContent = metrics.pendentes; document.querySelector('#progress').textContent = metrics.emAtendimento; document.querySelector('#solved').textContent = metrics.resolvidos; }
async function loadTable() { const params = new URLSearchParams(); [['search', 'search'], ['sectorFilter', 'setor'], ['statusFilter', 'status'], ['order', 'order']].forEach(([id, key]) => { const value = document.querySelector(`#${id}`).value; if (value) params.set(key, value); }); const list = await api(`/api/atendimentos?${params}`); rows.innerHTML = list.map((item) => `<tr><td><b>${item.protocolo}</b></td><td><b>${item.nome_cliente}</b><small>${item.contato}</small></td><td><b>${item.assunto}</b><small>${item.setor}</small></td><td>${dateFormat(item.criado_em)}</td><td>${badge(item.status)}</td><td><button class="view" data-id="${item.id}">Ver detalhes</button></td></tr>`).join(''); const message = document.querySelector('#tableMessage'); message.textContent = list.length ? '' : 'Nenhum atendimento encontrado para estes filtros.'; message.style.display = list.length ? 'none' : 'block'; }
async function refresh() { try { await Promise.all([loadDashboard(), loadTable()]); } catch (error) { if (error.message === 'Autenticação necessária.') window.location.assign('/login'); else alert(error.message); } }
async function openDetails(id) { const item = await api(`/api/atendimentos/${id}`); selectedId = id; document.querySelector('#modalProtocol').textContent = item.protocolo; document.querySelector('#modalName').textContent = item.nome_cliente; document.querySelector('#modalContact').textContent = item.contato; document.querySelector('#modalSubject').textContent = item.assunto; document.querySelector('#modalDate').textContent = dateFormat(item.criado_em); document.querySelector('#modalDescription').value = item.descricao; document.querySelector('#modalStatus').value = item.status; document.querySelector('#modalSector').value = item.setor; document.querySelector('#modalNotes').value = item.observacoes; modal.showModal(); }
document.querySelector('#logout').addEventListener('click', async () => { await api('/api/auth/logout', { method: 'POST' }); window.location.assign('/login'); });
document.querySelector('#refresh').addEventListener('click', refresh); ['sectorFilter', 'statusFilter', 'order'].forEach((id) => document.querySelector(`#${id}`).addEventListener('change', loadTable)); let searchTimer; document.querySelector('#search').addEventListener('input', () => { clearTimeout(searchTimer); searchTimer = setTimeout(loadTable, 280); });
rows.addEventListener('click', (event) => { const id = event.target.dataset.id; if (id) openDetails(id).catch((err) => alert(err.message)); });
document.querySelector('#detailsForm').addEventListener('submit', async (event) => { event.preventDefault(); try { await api(`/api/atendimentos/${selectedId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status: document.querySelector('#modalStatus').value, setor: document.querySelector('#modalSector').value, observacoes: document.querySelector('#modalNotes').value }) }); modal.close(); refresh(); } catch (error) { alert(error.message); } });
async function startDashboard() { const status = await api('/api/auth/status'); if (!status.authenticated) return window.location.assign('/login'); document.querySelector('#adminEmail').textContent = status.admin.email; window.scrollTo(0, 0); refresh(); }
startDashboard().catch(() => window.location.assign('/login'));
