const form = document.querySelector('#attendanceForm');
const alertBox = document.querySelector('#alert');
let step = 1;
function showStep(target) { step = target; document.querySelectorAll('.form-step').forEach((item) => item.classList.toggle('active', Number(item.dataset.step) === step)); document.querySelectorAll('.steps span').forEach((item, index) => item.classList.toggle('active', index + 1 <= step)); alertBox.classList.remove('show'); }
function showError(message) { alertBox.textContent = message; alertBox.classList.add('show'); }
document.querySelectorAll('.next').forEach((button) => button.addEventListener('click', () => { const fields = step === 1 ? ['nome_cliente', 'contato'] : ['assunto']; const missing = fields.some((name) => !new FormData(form).get(name)?.trim()); if (missing) return showError(step === 1 ? 'Informe seu nome e uma forma de contato.' : 'Escolha o assunto do seu atendimento.'); showStep(step + 1); }));
document.querySelectorAll('.back').forEach((button) => button.addEventListener('click', () => showStep(step - 1)));
form.addEventListener('submit', async (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(form)); if (!data.descricao.trim()) return showError('Descreva sua solicitação antes de continuar.'); const button = form.querySelector('[type="submit"]'); button.disabled = true; button.textContent = 'Registrando...'; try { const response = await fetch('/api/atendimentos', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); const attendance = await response.json(); if (!response.ok) throw new Error(attendance.error); form.hidden = true; document.querySelector('#clientName').textContent = attendance.nome_cliente.split(' ')[0]; document.querySelector('#sector').textContent = attendance.setor; document.querySelector('#protocol').textContent = attendance.protocolo; document.querySelector('#success').hidden = false; } catch (error) { showError(error.message || 'Não foi possível registrar sua solicitação.'); } finally { button.disabled = false; button.innerHTML = 'Registrar solicitação <span>→</span>'; } });
document.querySelector('#restart').addEventListener('click', () => { form.reset(); form.hidden = false; document.querySelector('#success').hidden = true; showStep(1); });
